set GUAJEPATH="C:\Users\Laura Moreno\Desktop\experimento\exp3"
set FISPRO="C:/Progra~1/FisPro/FISPRO-3.5/bin"
set GRAPHVIZ="C:/Program Files (x86)/Graphviz2.38/bin"
set FINGRAMSPATH=%GUAJEPATH%\libs\vismaps
set WEKAPATH=%GUAJEPATH%\libs\wekalib
set OREPATH=%GUAJEPATH%\libs\orelibs
set KEELPATH=%GUAJEPATH%\libs\keellibs
set XFUZZYPATH=%GUAJEPATH%\libs\xfuzzy
set ESPRESSOPATH=%GUAJEPATH%\libs\espresso
set EXECPATH=%GUAJEPATH%\libs\exec
set BATIKPATH=%GUAJEPATH%\libs\batik
set JAMAPATH=%GUAJEPATH%\libs\jamalib
set CPATHFISPRO=%FISPRO%\jar\plot.jar;%FISPRO%\jar\util.jar;%FISPRO%\jar\freehep-base.jar;%FISPRO%\jar\freehep-graphics2d.jar;%FISPRO%\jar\freehep-graphicsio.jar;%FISPRO%\jar\freehep-graphicsio-emf.jar;%FISPRO%\jar\freehep-graphicsio-gif.jar;%FISPRO%\jar\freehep-graphicsio-pdf.jar;%FISPRO%\jar\freehep-graphicsio-ps.jar
set CPATHFINGRAMS=%FINGRAMSPATH%\fingramsGenerator.jar
set CPATHEXEC=%EXECPATH%\commons-exec-1.3.jar
set CPATHKEEL=%KEELPATH%\SMOTE-I.jar;%KEELPATH%\RunKeel.jar
set CPATHWEKA=%WEKAPATH%\weka.jar
set CPATHORE1=%OREPATH%\ORE-UMU.jar;%OREPATH%\oreapi\ore-api.jar
set CPATHORE2=%OREPATH%\jena\arq.jar;%OREPATH%\jena\commons-logging-1.1.1.jar;%OREPATH%\jena\concurrent.jar;%OREPATH%\jena\icu4j_3_4.jar;%OREPATH%\jena\iri.jar;%OREPATH%\jena\jena.jar;%OREPATH%\jena\log4j-1.2.12.jar;%OREPATH%\jena\xercesImpl.jar
set CPATHORE3=%OREPATH%\jgoodies\forms-1.1.0.jar;%OREPATH%\pellet\aterm-java-1.6.jar;%OREPATH%\pellet\pellet.jar
set CPATHORE4=%OREPATH%\owlapi\commons-lang-2.2.jar;%OREPATH%\owlapi\owlapi-api.jar;%OREPATH%\owlapi\owlapi-apibinding.jar;%OREPATH%\owlapi\owlapi-change.jar;%OREPATH%\owlapi\owlapi-debugging.jar;%OREPATH%\owlapi\owlapi-dig1_1.jar;%OREPATH%\owlapi\owlapi-functionalparser.jar;%OREPATH%\owlapi\owlapi-functionalrenderer.jar;%OREPATH%\owlapi\owlapi-impl.jar;%OREPATH%\owlapi\owlapi-krssparser.jar;%OREPATH%\owlapi\owlapi-metrics.jar;%OREPATH%\owlapi\owlapi-oboparser.jar;%OREPATH%\owlapi\owlxmlparser.jar;%OREPATH%\owlapi\owlapi-owlxmlrenderer.jar;%OREPATH%\owlapi\owlapi-rdfapi.jar;%OREPATH%\owlapi\owlapi-rdfxmlparser.jar;%OREPATH%\owlapi\owlapi-rdfxmlrenderer.jar;%OREPATH%\owlapi\owlapi-util.jar
set CPATHORE5=%OREPATH%\xsd\relaxngDatatype.jar;%OREPATH%\xsd\xsdlib.jar;%OREPATH%\ws-client\commons-logging-api.jar;%OREPATH%\ws-client\em-client.jar
set CPATHORE=%CPATHORE1%;%CPATHORE2%;%CPATHORE3%;%CPATHORE4%;%CPATHORE5%
set CPATHXFUZZY=%XFUZZYPATH%;%XFUZZYPATH%\xfuzzy.jar
set CPATHBATIK=%BATIKPATH%\batik-anim.jar;%BATIKPATH%\batik-awt-util.jar;%BATIKPATH%\batik-bridge.jar;%BATIKPATH%\batik-codec.jar;%BATIKPATH%\batik-css.jar;%BATIKPATH%\batik-dom.jar;%BATIKPATH%\batik-ext.jar;%BATIKPATH%\batik-extension.jar;%BATIKPATH%\batik-gui-util.jar;%BATIKPATH%\batik-gvt.jar;%BATIKPATH%\batik-parser.jar;%BATIKPATH%\batik-script.jar;%BATIKPATH%\batik-svg-dom.jar;%BATIKPATH%\batik-svggen.jar;%BATIKPATH%\batik-swing.jar;%BATIKPATH%\batik-transcoder.jar;%BATIKPATH%\batik-util.jar;%BATIKPATH%\batik-xml.jar;%BATIKPATH%\xml-apis-ext.jar
set CPATHJAMA=%JAMAPATH%\Jama-1.0.2.jar
set CPATHGUAJE=%GUAJEPATH%\libs\guajelib\GUAJE-v3.0.jar
set CPATH=%CPATHGUAJE%;%CPATHFISPRO%;%CPATHFINGRAMS%;%CPATHEXEC%;%CPATHWEKA%;%CPATHKEEL%;%CPATHXFUZZY%;%CPATHORE%;%CPATHBATIK%;%CPATHJAMA%
java -Xmx512m -Despressopath=%ESPRESSOPATH% -Dgraphpath=%GRAPHVIZ% -Djava.library.path=%FISPRO% -Dpellet.configuration=file:config\pellet.properties -Dlog4j.configuration=file:config\log4j.properties -classpath %CPATH% kbct.MainKBCT